services:
  mysql:
    image: mysql:8.0
    container_name: home_automation_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  mongo:
    image: mongo:8.0
    container_name: home_automation_logs
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - "mongo_data:/data/db"

volumes:
  db_data:
  mongo_data:
