version: "1.0.1"
id: "9a0b1c2d-3e4f-5678-90ab-cdef12345678"
pages:
  - id: "f47ac10b-58cc-4372-a567-0e02b2c3d479"
    title: "Lights"
    buttons:
      - id: "123e4567-e89b-12d3-a456-426614174000"
        title: "Flower pot"
        subtitle: "brightness"
        state: "active"
        value: 50
        default: true
        content:
          text: ""
          icon: "lights"

      - id: "550e8400-e29b-41d4-a716-446655440000"
        title: "movie"
        subtitle: "set scene"
        state: "active"
        value: 50
        default: false
        content:
          text: ""
          icon: "lights"
