pages:
  - id: "halo.page.1"
    title: "Lights"
    buttons:
      - id: "halo.button.1"
        title: "flower pot"
        subtitle: "brightness"
        state: "active"
        value: 50
        default: "true"
        content:
          - text: ""
            icon: "lights"

      - id: "halo.button.2"
        title: "movie"
        subtitle: "set scene"
        state: "active"
        value: 50
        default: "false"
        content:
          - text: ""
            icon: "lights"
